name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Fix permissions before checkout
      run: |
        sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/product-api-ci-cd || true
        sudo chmod -R 755 /home/ubuntu/actions-runner/_work/product-api-ci-cd || true

    - uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull tharukal/product-api-ci-cd:latest

    - name: Delete old docker container
      run: |
        docker stop product-api-ci-cd || true
        docker rm -f product-api-ci-cd || true

    - name: Run Docker Container
      run: |
        docker run -d -p 5000:5000 --name product-api-ci-cd \
          -e NODE_ENV=production \
          -e PORT=5000 \
          -e MONGO_URI=${{ secrets.MONGO_URI }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -e JWT_EXPIRE=30d \
          tharukal/product-api-ci-cd:latest